name: Lint
on: [push, pull_request]
env:
  BASEDIR: file://`pwd`
jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('.github/workflows/lint.yml') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: curl -s -S --retry 3 $BASEDIR/tests/install.sh | bash -
      - run: sudo apt-get install shellcheck
      - run: sudo snap install shfmt
      - run: curl -s -S --retry 3 $BASEDIR/tests/script.sh | bash -
      - run: shellcheck $(shfmt -f tests)
      - run: shfmt -d -i 4 -sr $(shfmt -f tests)
